"""Update models

Revision ID: 91db5470d5b7
Revises: 670eb9ae6aed
Create Date: 2023-06-20 06:24:11.169628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91db5470d5b7'
down_revision = '670eb9ae6aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('clicks')
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_url', sa.String(), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('short_url')

    op.create_table('clicks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url_id', sa.INTEGER(), nullable=True),
    sa.Column('clicked_at', sa.DATETIME(), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('analytics')
    # ### end Alembic commands ###
